server:
  port: 8080
spring:
  application:
    name: lotto-payment
  datasource:
    url: jdbc:postgresql://localhost:5432/user_lotto_info?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: 192.168.0.20:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: email-group
      auto-offset-reset: earliest

secret:
