server:
  port: 8081
spring:
  application:
    name: lotto-payment
  datasource:
    url: jdbc:postgresql://localhost:5432/user_lotto_info?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: 192.168.0.20:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

token:
  secret: guess_secretguess_secretguess_secretguess_secret

kafka:
  product:
    name: history-topic