server:
  port: 8080
spring:
  application:
    name: lotto-payment
  datasource:
    url: jdbc:postgresql://postgres-service:5432/lotto?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${user}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: 35.184.196.158:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

token:
  secret: guess_secretguess_secretguess_secretguess_secret

kafka:
  product:
    name: history-topic